# Generated by Django 3.1.7 on 2022-06-12 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0003_qrcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qrcode',
        ),
    ]
